### PR TITLE
Allow node red to play/pause/stop/next/prev

### PR DESCRIPTION
**Pull request by ddanier**

### CODE REVIEW

**Comment by Alex9779** [comment]
Thanks, looks good, I am going to review again and then push a new version...

**Comment by ddanier** [comment]
Hi @Alex9779 

Are you going to release this some time soon? Thank you!

**Comment by Alex9779** [comment]
just released, sorry for the inconvenience this might have caused...

**Comment by ddanier** [comment]
Thank you!

**Pull request merged**
